pragma Singleton
import QtQuick

/*
 * GENERATED -- do not hand-edit. Source: design/tokens/*.json.
 * Regenerate with: npm run tokens:build
 */
QtObject {
  readonly property color backgroundDefault: "#0a0a0a"
  readonly property color surface1Default: "#141414"
  readonly property color surface2Default: "#1c1c1c"
  readonly property color surface3Default: "#262626"
  readonly property color foregroundDefault: "#fafafa"
  readonly property color foregroundMutedDefault: "#a3a3a3"
  readonly property color foregroundSubtleDefault: "#737373"
  readonly property color borderDefault: "#262626"
  readonly property color borderStrongDefault: "#404040"
  readonly property color primaryDefault: "#fafafa"
  readonly property color primaryForegroundDefault: "#171717"
  readonly property color primarySoftDefault: Qt.rgba(0.980392, 0.980392, 0.980392, 0.08)
  readonly property color successDefault: "#10b981"
  readonly property color successForegroundDefault: "#04150f"
  readonly property color warnDefault: "#f59e0b"
  readonly property color warnForegroundDefault: "#1f1400"
  readonly property color infoDefault: "#0ea5e9"
  readonly property color infoForegroundDefault: "#041b26"
  readonly property color destructiveDefault: "#ef4444"
  readonly property color destructiveForegroundDefault: "#1f0a0a"
  readonly property color focusDefault: "#fafafa"
  readonly property var glowLiveDefault: "0 0 0 1px rgba(16,185,129,.35), 0 0 24px rgba(16,185,129,.18)"
  readonly property color osdLabelDefault: "#ff9a2e"
  readonly property color osdLabelMediaDefault: "#2dd4bf"
  readonly property color osdValueDefault: "#ffffff"
  readonly property color osdOutlineDefault: Qt.rgba(0, 0, 0, 0.85)
  readonly property var durationFastDefault: "120ms"
  readonly property var durationBaseDefault: "180ms"
  readonly property var durationSlowDefault: "260ms"
  readonly property var durationPageDefault: "420ms"
  readonly property var easeOutDefault: "cubic-bezier(.2,.7,.2,1)"
  readonly property var easeInOutDefault: "cubic-bezier(.6,0,.2,1)"
  readonly property var xsDefault: "6px"
  readonly property var smDefault: "8px"
  readonly property var mdDefault: "16px"
  readonly property var lgDefault: "20px"
  readonly property var shadow1Default: "0 1px 2px rgba(0,0,0,.40)"
  readonly property var shadow2Default: "0 8px 24px rgba(0,0,0,.45)"
  readonly property var shadow3Default: "0 24px 64px rgba(0,0,0,.55)"
  readonly property var baseDefault: "4px"
  readonly property var step1: "4px"
  readonly property var step2: "8px"
  readonly property var step3: "12px"
  readonly property var step4: "16px"
  readonly property var step5: "20px"
  readonly property var step6: "24px"
  readonly property var step8: "32px"
  readonly property var step10: "40px"
  readonly property var step12: "48px"
  readonly property var step16: "64px"
  readonly property var step20: "80px"
  readonly property var step24: "96px"
  readonly property string fontSansDefault: "Inter"
  readonly property string fontMonoDefault: "Geist Mono"
  readonly property string fontDisplayDefault: "Geist"
  readonly property string fontArabicDefault: "IBM Plex Sans Arabic"
  readonly property var scaleDisplaySize: "clamp(2.25rem, 5vw, 3.75rem)"
  readonly property var scaleDisplayLineHeight: "1.05"
  readonly property var scaleDisplayTracking: "-0.02em"
  readonly property var scaleH1Size: "2rem"
  readonly property var scaleH1LineHeight: "1.15"
  readonly property var scaleH1Tracking: "-0.015em"
  readonly property var scaleH2Size: "1.5rem"
  readonly property var scaleH2LineHeight: "1.2"
  readonly property var scaleH2Tracking: "-0.01em"
  readonly property var scaleH3Size: "1.25rem"
  readonly property var scaleH3LineHeight: "1.3"
  readonly property var scaleH3Tracking: "0"
  readonly property var scaleBodySize: "1rem"
  readonly property var scaleBodyLineHeight: "1.6"
  readonly property var scaleBodyTracking: "0"
  readonly property var scaleSmSize: "0.875rem"
  readonly property var scaleSmLineHeight: "1.55"
  readonly property var scaleSmTracking: "0"
  readonly property var scaleCaptionSize: "0.8125rem"
  readonly property var scaleCaptionLineHeight: "1.45"
  readonly property var scaleCaptionTracking: "0"
  readonly property var scaleLabelSize: "0.75rem"
  readonly property var scaleLabelLineHeight: "1.3"
  readonly property var scaleLabelTracking: "0.08em"
  readonly property var scaleMonoSize: "0.875rem"
  readonly property var scaleMonoLineHeight: "1.5"
  readonly property var scaleMonoTracking: "0"
}
